cutoff_dependent_parameters:
  cutoff: 160
  rescaling_parameter: 3167.16

model_parameters:
  phi0: 2.3675
  d_phi0: -0.0000013683
  chi0: 0.
  d_chi0: 0.
  a0: 1.
  specific_model_parameters:
    M: 0.00327688
    MInt: 0.03162
    Mh: 0.0000611935

error_analysis_parameters:
  tau1: 0.000005
  tau2: 0.000001

technical_parameters:
  continuation: True #can be True or False
  N: 32
  steps_number: 10000
  start_iter: 30000 #should be the multiplication of 10000
  initial_time_step: 0.0001
  output_dir_path: '../Results/ResultsForStarobinskyModel2'
  write_separate_potential_energy: True
  special_comment: ''
  parameters_included_in_files_names:
    cutoff_dependent_parameters:
      - 'cutoff'
    technical_parameters:
      - 'N'
    specific_model_parameters:
      - 'MInt'
      - 'Mh'
